services:
  minitwit:
    build:
      context: ./itu-minitwit
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:5273"
    environment:
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
    depends_on:
      - grafana
      - prometheus

  prometheus:
    build: 
      dockerfile: ./Dockerfile
      context: ./itu-minitwit/monitoring/prometheus
    image: prometheus_image
    container_name: prometheus
    ports:
      - "9090:9090"

  grafana:
    build: 
      dockerfile: ./Dockerfile
      context: ./itu-minitwit/monitoring/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}