{
 "title": "Everything ASP.NET Core ",
 "description": "ASP.NET Core metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_active_requests{job=~\"$job\"},instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"minitwit\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_received_total{status=~\"[45]..\", job=\"minitwit\"}[5m])) or on() vector(0)) \n/\nsum(rate(http_requests_received_total{job=\"minitwit\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "(sum(rate(http_requests_received_total{code=~\"4..\", job=\"minitwit\"}[5m])) or on() vector(0)) \n/ \nsum(rate(http_requests_received_total{job=\"minitwit\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "(sum(rate(http_requests_received_total{status=~\"5..\", job=\"minitwit\"}[5m])) or on() vector(0)) \n/\n sum(rate(http_requests_received_total{job=\"minitwit\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints last 24h",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{job=\"minitwit\"}[$__range])) by (endpoint) \n/ \nignoring(endpoint) group_left \nsum(increase(http_requests_received_total{job=\"minitwit\"}[$__range]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"minitwit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", error_type!=\"\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request methods",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{job=\"minitwit\"}) by (method)",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{job=\"minitwit\"}) by (protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"2..\", job=\"minitwit\"}[5m])) / sum(rate(http_requests_received_total{job=\"minitwit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{job=\"minitwit\"}[1m]))",
     "legendFormat": "active requests"
    }
   ]
  },
  {
   "title": "Top 10 Unhandled Exception Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_requests_received_total{status=\"500\", job=\"minitwit\"}[5m])) by (endpoint))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Recent Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"docker\"} \n  != \"negative structured metadata bytes\" \n  != \"failed to update managedFields\"\n| pattern `<_> | <_> <_> - <user> [<_>] \"<method> <path> <_>\" <status> <_>`\n| line_format \"{{if .status}}{{.status}} | {{.method}} {{.path}}{{else}}{{__line__}}{{end}}\""
    }
   ]
  }
 ]
}