---
- name: Provision and deploy MiniTwit
  hosts: minitwit_servers
  become: true

  vars:
    image_name: "minitwitimage"
    container_name: "minitwit"
    minitwit_app_instances: 2
    app_port: "5273"
    db_volume: "minitwit_db_volume"
    domain_name: "{{ domain_name | default('minitwit.tech', true) }}"
    letsencrypt_email: "{{ letsencrypt_email | default('bror@live.dk', true) }}"
    # These fall back to 'latest' if run locally via Vagrant
    dockerhub_user: "{{ dockerhub_username | default('sn3ke') }}"
    app_version: "{{ image_tag | default('latest') }}"
    # DigitalOcean API token for floating IP failover (pass via -e do_api_token=<token>)
    do_api_token: "{{ do_api_token | default('', true) }}"

  roles:
    - minitwit
