# Ansible Inventory Template - Production DigitalOcean
# Generated by Terraform

[web_servers]
minitwit-lb-primary ansible_host=${primary_web_ip} ansible_user=root ansible_ssh_private_key_file=${ssh_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
minitwit-lb-secondary ansible_host=${secondary_web_ip} ansible_user=root ansible_ssh_private_key_file=${ssh_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[minitwit_lb_primary]
minitwit-lb-primary

[minitwit_lb_secondary]
minitwit-lb-secondary

[minitwit_servers:children]
minitwit_lb_primary
minitwit_lb_secondary

[db_servers]
${db_ip} ansible_user=root ansible_ssh_private_key_file=${ssh_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[minitwit:children]
web_servers
db_servers

[minitwit:vars]
deployment_mode=production
ansible_user=root
ansible_ssh_private_key_file=${ssh_key_path}
ansible_connection=ssh
project_name=${project_name}
# Pass the Database IP to the Web Server
db_internal_ip=${db_ip}
keepalived_virtual_ip=${floating_ip}