# Ansible Inventory Template - Local Development
# Generated by Terraform

[local]
localhost ansible_connection=local

[minitwit]
localhost

[minitwit:vars]
deployment_mode=vagrant
dockerhub_username=${dockerhub_username}
image_tag=${image_tag}
domain_name=${domain_name}
grafana_admin_user=${grafana_admin_user}
grafana_admin_password=${grafana_password}
