# Ansible Inventory Template - Production DigitalOcean
# Generated by Terraform

[web_servers]
${web_ip} ansible_user=root ansible_ssh_private_key_file=${ssh_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[db_servers]
${db_ip} ansible_user=root ansible_ssh_private_key_file=${ssh_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[minitwit:children]
web_servers
db_servers

[minitwit:vars]
deployment_mode=production
ansible_user=root
ansible_ssh_private_key_file=${ssh_key_path}
ansible_connection=ssh
project_name=${project_name}
# Pass the Database IP to the Web Server
db_internal_ip=${db_ip}