# Ansible Inventory Template - Production DigitalOcean
# Generated by Terraform

[production]
${droplet_ip} ansible_user=root ansible_ssh_private_key_file=${ssh_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[minitwit]
${droplet_ip}

[minitwit:vars]
deployment_mode=production
ansible_user=root
ansible_ssh_private_key_file=${ssh_key_path}
ansible_connection=ssh
project_name=${project_name}
